<?php
/**
 * Created by PhpStorm.
 * User: Руслан
 * Date: 13.10.2016
 * Time: 22:48
 */

namespace maestroprog\saw\service;

use maestroprog\saw\command\TaskRes;
use maestroprog\saw\command\TaskRun;
use maestroprog\saw\entity\Command;
use maestroprog\saw\entity\Task;
use maestroprog\saw\library\Executor;
use maestroprog\esockets\debug\Log;
use maestroprog\saw\library\Factory;
use maestroprog\saw\library\worker\Core;

/**
 * Воркер, использующийся входным скриптом.
 */
final class Init extends Worker
{
    use Executor;

    public $controller_path = 'controller.php';

    /**
     * @throws \Exception
     */
    public function start()
    {
        $this->core = new Core($this->sc, $this->worker_app, $this->worker_app_class);
        $this->dispatcher = Factory::getInstance()->createDispatcher([
            new Command(TaskRun::NAME, TaskRun::class),
            new Command(
                TaskRes::NAME,
                TaskRes::class,
                function (TaskRes $context) {
                    $this->core->receiveTask(
                        $context->getRunId(),
                        $context->getResult()
                    );
                }
            ),
        ]);
    }

    public function run()
    {
        parent::run(); // TODO: Change the autogenerated stub
        $this->core->app->end();
    }


    public function addTask(Task $task)
    {
        $this->dispatcher->create(TaskRun::NAME, $this->sc)
            ->onError(function () use ($task) {
                throw new \Exception('Failed run Task ' . $task->getName());
            })
            ->run(TaskRun::serializeTask($task));
    }

    /**
     * @param array $config
     * @return Worker
     * @throws \Exception
     */
    public static function create(array $config): Worker
    {
        $init = self::getInstance();
        if (!$init->init($config)) {
            throw new \Exception('Cannot initialize Init worker');
        }
        Log::log('configured. input...');
        try {
            if (!$init->connect()) {
                // controller autostart util
                Log::log('controller starting');
                $before_run = microtime(true);
                $init->exec($init->controller_path);
                Log::log('started');
                $after_run = microtime(true);
                usleep(10000); // await for run controller Saw
                $try = 0;
                while (true) {
                    $try_run = microtime(true);
                    if (!$init->connect()) {
                        usleep(10000);
                    }
                    Log::log(sprintf(
                        'run: %f, exec: %f, connected: %f',
                        $before_run,
                        $after_run - $before_run,
                        $try_run - $after_run
                    ));
                    Log::log('before run time: ' . $before_run);

                    if ($try++ < 10) {
                        throw new \Exception('Attempts were unsuccessfully');
                    }
                }
            }
            $init->sc->send('HELLO');
            $init->start();
            Log::log('Init started');
            register_shutdown_function(function () use ($init) {
                Log::log('work start');
                //$init->work();
                Log::log('work end');

                $init->stop();
                Log::log('closed');
            });
            return $init->setTask(Factory::getInstance()->createTaskManager($init));
        } catch (\Exception $e) {
            Log::log(sprintf('Saw connect or start failed with error: %s', $e->getMessage()));
            throw new \Exception('Framework starting fail', 0, $e);
        }
    }
}
